server:
  port: 5000
  servlet:
    context-path: "/gateway"

logging:
  level.: INFO

spring.mvc.async.request-timeout: -1 #-1 means infinity

event:
  source:
    timeout: -1

core.version: @project.version@

service:
  enableScheduling: true

schedulers:
  sensorValueUpdater:
    enabled: true
    initialDelay: 6000
    fixedDelay: 6000